<?php

/**
 * Implements hook_menu(). 
 */
function mesh_add_menu() {
  $items['mesh-add'] = array(
    'title'             => 'Development page for MeSH Add',
    'page callback'     => 'mesh_add_dev',
    'access arguments'  => array('access mesh content'),
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
function mesh_add_permission() {
  return array(
    'access mesh content' => array(
      'title' => t('Access MeSH Add content'),
      'description' => t('Allows user to import MeSH headings'),
    ),
  );
}

/**
 * hook_menu() callback for /mesh-add
 * @return string 
 */
function mesh_add_dev() {
  
  return '';
}
